Downgrade Pillow
Fixes error with missing util

> /usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py in <module>
     35 from . import Image
     36 from ._deprecate import deprecate
---> 37 from ._util import is_directory, is_path
     38 
     39 

ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.8/dist-packages/PIL/_util.py)